### ISSUE TITLE
centrometal pitanjce

### ISSUE THREAD

**Issue by toma9996** [9a4gl/hass-centrometal-boiler#1]
Pozdrav, naletio sam na tvoj github tražeći način kako da iz pelteca izvučem neke informacije vezano uz rad kotla. Ne koristim HA, već ST + sharptools i razmišljam da bi bilo fora imati u Sharptoolsima informaciju o statusu kotla, temperaturi vode i slično.

Nisam programer, probao sam iz tvog koda izvući info kako da dohvatim te informacije, pretpostavljam da postoji neki rest api, ali nemam pojma što, kako.

Imaš li ti neku ideju kako da dohvatim te informacije, pretpostavljam da ne postoji nigdje kvalitetna dokumentacija od samog vendora.

Sorry što sam ovako uletio iz neba, pa u rebra :-) ali ako imaš nešto što bi mi pomoglo oko ovoga, bio bi ti super zahvalan.

Thx

**Comment by 9a4gl** [comment]
Ne znam ništa o Sharptoolsima a koliko vidim to je nešto closed source i komercijalno. Home assistant ima politiku da svaka integracija mora biti bazirana na python librariju koje se može iskoristiti i za druge projekte. Tj. da oni koji participiraju u home assistantu doprinose i drugim projektima. Zbog toga je dio koji komunicira sa peći, tj. sa centrometalovim serverima u posebnom python projektu https://github.com/9a4gl/py-centrometal-web-boiler
