### ISSUE TITLE
dependency issue 2023.3.0 version

### ISSUE THREAD

**Issue by toma9996** [9a4gl/hass-centrometal-boiler#3]
Hi I'm getting dependency issue after update to 2023.3.0

Unable to install package py-centrometal-web-boiler==0.0.51: ERROR: Cannot install py-centrometal-web-boiler==0.0.51 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

**Comment by 9a4gl** [comment]
Fixed, please upgrade

**Comment by toma9996** [comment]
Thanks. It's working now.
