### ISSUE TITLE
Problem setting up

### ISSUE THREAD

**Issue by girafhacker** [9a4gl/hass-centrometal-boiler#4]
I have this problem, when fill in my credentials and click on submit it just pops back to empty login screen(the screen where you fill in your credentials).
and this is the log file.

``` This error originated from a custom integration.

Logger: custom_components.centrometal_boiler.config_flow
Source: custom_components/centrometal_boiler/config_flow.py:47
Integration: Centrometal Boiler System (documentation, issues)
First occurred: 3:13:54 PM (2 occurrences)
Last logged: 3:28:12 PM

Unexpected exception (my email)
Traceback (most recent call last):
  File "/config/custom_components/centrometal_boiler/config_flow.py", line 47, in async_step_user
    deviceCollection = await try_connection(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/centrometal_boiler/config_flow.py", line 82, in try_connection
    gotConfiguration = await web_boiler_client.get_configuration()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/centrometal_web_boiler/WebBoilerClient.py", line 41, in get_configuration
    self.data.parse_installations(self.http_client.installations)
  File "/usr/local/lib/python3.11/site-packages/centrometal_web_boiler/WebBoilerDeviceCollection.py", line 127, in parse_installations
    self[serial]["product"] = device["product"]
                              ~~~~~~^^^^^^^^^^^
KeyError: 'product'
```

**Comment by 9a4gl** [comment]
Hm, no idea, what boiler do you have?

**Comment by girafhacker** [comment]
Peltec 24 cm wifibox
peltec lambda 24 kw v2.83_30L

**Comment by 9a4gl** [comment]
Hm, I have peltec 36 lambda with wifibox, shall work, please add following to your configuration.yaml
```
logger:
  default: info
  logs:
    custom_components: debug
    custom_components.centrometal_boiler: debug
    centrometal_web_boiler: debug
    websocket: debug

```
And try again, let's see if log will show a bit more usefull info. But I am afraid the easiest way would be if you give me credentials and I debug that locally. I suggest you contact me over whatsapp +385 91 185 7050

BR

**Comment by girafhacker** [comment]
which web applications do you use? to manage the boiler.
And is that the same credentials as you use in HA

**Comment by 9a4gl** [comment]
> which web applications do you use? to manage the boiler. And is that the same credentials as you use in HA

WEB_BOILER_WEBROOT = 'https://www.web-boiler.com'

**Comment by girafhacker** [comment]
```
Logger: centrometal_web_boiler.HttpClient
Source: custom_components/centrometal_boiler/config_flow.py:79
Integration: Centrometal Boiler System ([documentation](https://github.com/9a4gl/hass-centrometal-boiler), [issues](https://github.com/9a4gl/hass-centrometal-boiler/issues))
First occurred: 1:42:36 PM (2 occurrences)
Last logged: 1:42:36 PM

HttpClient::__loginCheck cannot find loading div element (my email)
Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/centrometal_web_boiler/HttpClient.py", line 147, in login await self.__login_check() File "/usr/local/lib/python3.11/site-packages/centrometal_web_boiler/HttpClient.py", line 141, in __login_check raise Exception("HttpClient::__loginCheck cannot find loading div element") Exception: HttpClient::__loginCheck cannot find loading div element (my email)
```

this is a new log

**Comment by 9a4gl** [comment]
Are you sure you have connectivity to www.web-boiler.com ? Looks some unexpected http content is received, do you have some transparent proxy or?

**Comment by girafhacker** [comment]
> Are you sure you have connectivity to [www.web-boiler.com](http://www.web-boiler.com) ? Looks some unexpected http content is received, do you have some transparent proxy or?

If I use chrome I can log in on ''https://www.web-boiler.com/''

**Comment by girafhacker** [comment]
> [www.web-boiler.com](http://www.web-boiler.com)


I check it via the web card in HA, and I can't log in there either.
Is it possible that HA does something?

ps I run HA on Proxmox virtiual machine

**Comment by 9a4gl** [comment]
> ps I run HA on Proxmox virtiual machine

then it is up to your setup, I have never used proxmox, no idea

**Comment by girafhacker** [comment]
> then it is up to your setup, I have never used proxmox, no idea

oke thanks for your help.
you will hear when I fixed the problem

**Comment by girafhacker** [comment]
is it possible that you need a secure connection to log in.
If I log in with the wrong credentials I get this error.
```Traceback (most recent call last):
  File "/config/custom_components/centrometal_boiler/config_flow.py", line 47, in async_step_user
    deviceCollection = await try_connection(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/centrometal_boiler/config_flow.py", line 81, in try_connection
    raise Exception(f"Login to Centrometal boiler server failed {email}")
Exception: Login to Centrometal boiler server failed gsdfg
```

**Comment by 9a4gl** [comment]
What do you mean by secure connection, yes https must be used, server does not allow http.

**Comment by 9a4gl** [comment]
Seems to be issue related to setup and network environment
