### ISSUE TITLE
Values not updating after some time

### ISSUE THREAD

**Issue by zdimic1** [9a4gl/hass-centrometal-boiler#5]
Hi, 

I have a problem that i have to restart HA once a day because the values are not being updated any more.
After restart it works sometimes for half a day sometimes one day.

Also, on the picture of the boiler i have visible only boiler and pellet tank,, no buffer and no hot water tank. (on official Centrometal portal I see everything).

Peltec Lambda 36KW with buffer and water tank.
(ak je zgodnije možemo i na hrvatskom)

Thanks,

Best regards

**Comment by 9a4gl** [comment]
Isti sam problem i ja imao, jedan problem sam popravio no nije isključeno da ih ima još. To se pojavilo nakon jednog HA ažuriranja nedavno. Ja ima 0.0.46 koji ispravlja taj jedan bug i gledam sada mi pokazuje ispravno. Imaš i ti 0.0.46 ili?

**Comment by zdimic1** [comment]
Nemam pojma koja verzija je bila ali sigurno nije 0.0.46 nego neka od prije mjesec i nešto dana.
Nisam mogao provjeriti verziju jer sam ručno instalirao plugin kroz ssh, a ne prek GUI-ja pa mi ga tamo nije ni pokazivalo.

Napravio sam update, međutim još nema ovih slika pufera i bojlera na kartici... za update parametara budem malo pratio pa javim.

**Comment by 9a4gl** [comment]
Uf, tako je teško updejtati. Preporučam da koristiš HACS, naime često sa updateom HA stvar se raspadne, dogodilo se to već 5-6 puta.

**Comment by serviser** [comment]
hi
ja imam 0.0.46 i isto imam gornji problem. 
<img width="955" alt="Posnetek zaslona 2023-10-20 151304" src="https://github.com/9a4gl/hass-centrometal-boiler/assets/75380708/672d4c3f-e4f5-45f6-8c2f-da65a0a32c05">

**Comment by zdimic1** [comment]
Napravio sam sada instalaciju preko HACS-a. Nadam se da je to pregazilo staru instalaciju? 
Ako nije može savjet kako ju zgaziti ili kako napraviti ručni update?

Hvala.

**Comment by 9a4gl** [comment]
Uf ne znam kako te sa ssh zgaziit, makni je, rebootaj, nemam bolji savjet. A na slici ti je ona peć sa pirolizom biotec a ne peltec, to je nešto isto krivo. Vidi
https://github.com/9a4gl/lovelace-centrometal-boiler-card
trebao sam odrediti device_type no ako neće onda
type: custom:centrometal-boiler-card
device_type: peltec
no nisam vidio slučaj da neće

**Comment by zdimic1** [comment]
Ovo s Biotec-om nije moj kotao :-) ( vidi tko je postao )
kod mene je na slici peltec i ok je samo nema pufera i bojlera

**Comment by 9a4gl** [comment]
> Ovo s Biotec-om nije moj kotao :-) ( vidi tko je postao ) kod mene je na slici peltec i ok je samo nema pufera i bojlera

Skužio kasnije :)

**Comment by 9a4gl** [comment]
Ovako, ajde u configuration.yaml dodajte:

> logger:
>   default: info
>   logs:
>     custom_components.centrometal_boiler: debug
>     centrometal_web_boiler: debug
> 
vidi na kraju https://github.com/9a4gl/hass-centrometal-boiler
restajtajte, pa kad prestane raditi downloadjte cijeli log i pošaljite pa ću pogledati gdje se crashalo. 
Kod mene je već par dana ok.

**Comment by zdimic1** [comment]
Nakon remove i ponovo instalacije, reboot i sl. opet nema na slici pufera i bojelra.

Ovo dobijem (warning) u log-u nakon restarta:

Logger: centrometal_web_boiler.WebBoilerDeviceCollection
Source: custom_components/centrometal_boiler/sensors/WebBoilerGenericSensor.py:154
Integration: Centrometal Boiler System ([documentation](https://github.com/9a4gl/hass-centrometal-boiler), [issues](https://github.com/9a4gl/hass-centrometal-boiler/issues))
First occurred: 4:22:16 PM (1 occurrences)
Last logged: 4:22:16 PM

WebBoilerDevice::get_parameter parameter B_zlj does not exist, creating one


![image](https://github.com/9a4gl/hass-centrometal-boiler/assets/145553012/072c3b00-05b3-4618-9b85-16dbce8a540f)

**Comment by 9a4gl** [comment]
> WebBoilerDevice::get_parameter parameter B_zlj does not exist, creating one

To je ok
Izbaci device, restart home assistanta, pa dodaj ponovno centrometal device.. takvi problemi su često nakon upgrejda ako se nešto preimenuje

**Comment by 9a4gl** [comment]
Dakle, ovo me napatilo dosta, a bio sam i u gužvi pa nisam stigao. Uglavnom, koristim neki stari library koji nije održavan za websockete, i izgleda je python promjenio što vraća jedna funkcija. Locirao sam grešku, nekak pokušaj fixa sam releaseo, budem sada pratio da li to bude to. Kod mene se to događalo nekan nakon dan nekada nakon dva dana, uglavnom kad je bio connection timeout. Eto, stavi zadnju verziju pa pratimo jel bude bolje.

**Comment by zdimic1** [comment]
Updejtao, pa javim kako će se ponašati. U zadnje vrijeme je malo radilo malo nije, bilo je nekad perioda od nekoliko sati do nešto manje od cijelog dana da nije učitavao podatke, ali bi u nekom momentu proradilo samo od sebe.

**Comment by 9a4gl** [comment]
Meni radi pouzdano, tebi? Mogu zatvoriti ticket?

**Comment by serviser** [comment]
Jučer su imali održavanje portala pa nije radio, ali preko noči  ne znam zašto nije bilo ažuriranja...
![Zajeta slika](https://github.com/9a4gl/hass-centrometal-boiler/assets/75380708/4b12de01-8330-40df-ae5d-a8224ee2a488)

**Comment by zdimic1** [comment]
Meni za sada radi 1 dan jer je bio onaj ispad njihovog web-a iako nakon što je njihov portal ponovo proradio meni nije napravio update parametara, jučer sam restartao sistem, pa čekamo sad par dana,pa javim kako će ići.

**Comment by zdimic1** [comment]
Evo ga, opet ne radi i ovo su 2 greške između ostalih koje vidim da imaju veze sa Centrometalom, a nastale su 2-3 minute nakon zadnjeg updatea vrijednosti sa kotla u 11:46


Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:145
First occurred: 10:03:58 AM (2 occurrences)
Last logged: 11:48:02 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/centrometal_web_boiler/ws/client.py", line 112, in __main
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 425, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.

--------------------------------------------------------------------------

Logger: py.warnings
Source: runner.py:188
First occurred: 11:48:02 AM (2 occurrences)
Last logged: 11:48:02 AM

/usr/local/lib/python3.11/asyncio/base_events.py:1926: RuntimeWarning: coroutine 'WebBoilerWsClient.__init__.<locals>.on_disconnect' was never awaited handle = None # Needed to break cycles when an exception occurs.
/usr/local/lib/python3.11/asyncio/base_events.py:1926: RuntimeWarning: coroutine 'ClientSocket.on_disconnect' was never awaited handle = None # Needed to break cycles when an exception occurs.

**Comment by toma9996** [comment]
isto se događa i kod mene. zadnja verzija isto.

primjetio sam da se to dogodi u isto vrijeme kada mi router radi reconnect internet veze.

![image](https://github.com/9a4gl/hass-centrometal-boiler/assets/83392678/f256f67f-4cbb-4115-ae9d-e7e936e2ee8c)

![image](https://github.com/9a4gl/hass-centrometal-boiler/assets/83392678/6c63c861-a783-4b68-abec-25c5651b18b3)

**Comment by 9a4gl** [comment]
Dakle, sada i kod mene problem... Nije isti kao prošli puta već novi.. kod mene u 3:34:30, i da 3:33:21 je bio PPPOE reconnect na t-com optici, dakle isto očito povezano... super, bar sad znam kako to reproducirati...  jedino ne znam kada ću naći vremena za to.

**Comment by toma9996** [comment]
pomalo. nije žurba.

**Comment by 9a4gl** [comment]
Mislim da sam popravio, testirao nakon gubitka konekcije ponovno se spoji i radi dalje. Živi bili pa vidjeli koliko će dugo izdržati, do sljedeće verzije pythona...
