### ISSUE TITLE
url was not accepted as a valid repository

### ISSUE THREAD

**Issue by dabo5** [9a4gl/hass-centrometal-boiler#7]
Hi,
i can't add a custom repository in homeassistant because the URL is not accepted (https://github.com/9a4gl/hass-centrometal-boiler).
is there a quick solution?
I use homeassistant version 2024.10.1 as lxc on proxmox, so I want to avoid manual installation.
thanks

**Comment by 9a4gl** [comment]
I never used proxmox, but previously someone reported it is not working on proxmox but later said it works on regular instalation. I recommand using HACS to install integration.

**Comment by dabo5** [comment]
Thank you for the super quick reply. I solved the problem. I had installed hacs using the wrong instructions. I had used the instructions for docker, but in fact hacs was very easy to install in the proxmox lxr using the instructions for "OS/Supervised".
I had only recently ordered the wifi module and have now installed the integration using your instructions...the homeassistant integration is a huge added value for me. A big thank you for that!
